config/routes.rb
Rails.application.routes.draw do
  
  root 'articles#index'

  #Single user log in - session
  # get 'signup', to: "users#new"
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 

  
  #Users
  resources :users
  
  
  #Articles 
  resources :articles do
     #Comments 
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                      length: {minimum: 5, maximum: 140}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    # http_basic_authenticate_with name: "dhh", password:
    # "secret", except: [:index, :show]
    
    def index
        @articles = Article.all
        # [#<Article id: 1, title: "hii", text: "bye1", ... ]

        # @articles = Article.connection.select_all("SELECT * FROM articles")
        # puts "@articles is: #{@articles.inspect}"
        # puts "@articles is: #{@articles.rows.first}"
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        #the line under just renders the hash created by saving an article from the page
        #there wasn't any database at that time so just the whole hash eas displayed.
        # render plain: params[:article].inspect
        
        #creating object from the model under global variable @article 
        #where the database :article is called

        # puts "params are: #{article_params.inspect}"

        @article = Article.new(article_params)
        # @article.user = need to connect current session with the database - need to get the user/article ID connected 
        
        #a message is saved to the database
        if @article.save
            redirect_to @article
        #and the pages is redirected to the main page
        else
            render "new"
        end

        # puts "article is #{article}"
        # puts "@article is #{@article}"

        
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render "edit"
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>

<%= render 'shared/errors' %>

 <p>
   <%= form.label :title %><br>
   <%= form.text_field :title %>
 </p>

 <p>
   <%= form.label :text %><br>
   <%= form.text_area :text %>
 </p>

 <p>
   <%= form.submit %>
 </p>

<% end %>

<%= link_to 'Back to articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render "articles/form"%>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "Sign up now!", new_user_path %>

<%= link_to "New article", new_article_path %>



<table>
    <tr>
      <th>Title</th>
      <th>Text</th>
    </tr>
   
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to "Edit", edit_article_path(article) %></td>
        <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </table>



   

app/views/articles/new.html.erb
<h1>Create new article here</h1>
   
   <%= render "articles/form"%>

   

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>


<h2>Comments</h2>
<%= render @article.comments %>



<h2>Add a comment:</h2>
<%= render "comments/form"%>



<%= link_to "Edit this article", edit_article_path(@article) %>

<%= link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

<%= link_to "Back to articles", articles_path %>